### ISSUE TITLE
Template et skin dans base/default

### ISSUE THREAD

**Issue by vmaph2m** [quadra-informatique/Magento-Module-Cybermut#1]
Bonjour,
Pouvez-vous mettre les templates et skin dans base/default ? En effet, si l'on a une interface personnalisée, les fichiers ne seront pas trouvés s'ils sont dans default/default.
Merci !

**Comment by mpasquin** [comment]
Bonjour,

Cette modification a été effectuée par @fusco en décembre dernier (commit 5bee1f4).
Elle est désormais disponible au téléchargement

Cordialement
