### ISSUE TITLE
url de retour

### ISSUE THREAD

**Issue by ahyear** [quadra-informatique/Magento-Module-Cybermut#8]
Bonjour,

La banque demande une url de retour.
Quel chemin dois-je noter?
serai-t-il possible de l'ajouter dans le readme.md?

Cordialement.

**Comment by real34** [comment]
Bonjour,

Les urls sont:

* url_retour_ok => http://example.com/cybermut/payment/success
* url_retour => http://example.com/cybermut/payment/notify
* url_retour_err => http://example.com/cybermut/payment/error

**Comment by mpasquin** [comment]
Bonjour,

L'URL a communqué à votre banque est du type : https://example.com/cybermut/payment/notify/

Si vous n'utilisez pas de cetificat SSL (ce qui n'est absolument pas recommandé), l'URL sera alors de type : http://example.com/cybermut/payment/notify/

Attention toutefois, cette URL n'est exacte que si vous avez : 
- activé l'utilisation des réécritures d'URL par le serveur web,
- désactivé l'ajout des codes des magasins dans l'URL
dans la configuration de votre Magento.

@real34 : Merci pour votre réponse rapide !

Cordialement.
